# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Thorfile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{couchrails}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Felipe Rodrigues"]
  s.date = %q{2010-04-16}
  s.description = %q{A Object Document Mapper for Rails 3 that implements ActiveModel. It is based on CouchRest}
  s.email = %q{couchrails@fratech.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "Thorfile"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Thorfile",
     "lib/couchrails.rb",
     "lib/couchrails/active_model.rb",
     "lib/couchrails/core/config.rb",
     "lib/couchrails/core/document.rb",
     "lib/couchrails/support/abstract_class.rb",
     "lib/couchrails/support/version.rb"
  ]
  s.homepage = %q{http://github.com/felipero/couchrails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Object Document Mapper for Rails 3 that implements ActiveModel}
  s.test_files = [
    "spec/amo_compliance_spec.rb",
     "spec/config_spec.rb",
     "spec/couchrails_active_model_spec.rb",
     "spec/models.rb",
     "spec/spec_helper.rb",
     "spec/spec.opts"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

