# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Thorfile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{couchrails}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Felipe Rodrigues"]
  s.date = %q{2010-04-16}
  s.description = %q{A Object Document Mapper for Rails 3 that implements ActiveModel. It is based on CouchRest}
  s.email = %q{couchrails@fratech.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "Thorfile"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Thorfile",
     "lib/couchrails.rb",
     "lib/couchrails/active_model.rb",
     "lib/couchrails/core/config.rb",
     "lib/couchrails/core/document.rb",
     "lib/couchrails/support/abstract_class.rb",
     "lib/couchrails/support/version.rb"
  ]
  s.homepage = %q{http://github.com/felipero/couchrails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Object Document Mapper for Rails 3 that implements ActiveModel}
  s.test_files = [
    "spec/amo_compliance_spec.rb",
     "spec/config_spec.rb",
     "spec/couchrails_active_model_spec.rb",
     "spec/models.rb",
     "spec/spec_helper.rb",
     "examples/helloworld/app/controllers/application_controller.rb",
     "examples/helloworld/app/controllers/posts_controller.rb",
     "examples/helloworld/app/helpers/application_helper.rb",
     "examples/helloworld/app/helpers/posts_helper.rb",
     "examples/helloworld/app/models/post.rb",
     "examples/helloworld/config/application.rb",
     "examples/helloworld/config/boot.rb",
     "examples/helloworld/config/environment.rb",
     "examples/helloworld/config/environments/development.rb",
     "examples/helloworld/config/environments/production.rb",
     "examples/helloworld/config/environments/test.rb",
     "examples/helloworld/config/initializers/backtrace_silencers.rb",
     "examples/helloworld/config/initializers/inflections.rb",
     "examples/helloworld/config/initializers/mime_types.rb",
     "examples/helloworld/config/initializers/secret_token.rb",
     "examples/helloworld/config/initializers/session_store.rb",
     "examples/helloworld/config/routes.rb",
     "examples/helloworld/db/migrate/20100416020456_create_posts.rb",
     "examples/helloworld/db/seeds.rb",
     "examples/helloworld/test/functional/posts_controller_test.rb",
     "examples/helloworld/test/performance/browsing_test.rb",
     "examples/helloworld/test/test_helper.rb",
     "examples/helloworld/test/unit/helpers/posts_helper_test.rb",
     "examples/helloworld/test/unit/post_test.rb",
     "examples/post_example.rb",
     "spec/spec.opts"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<couchrest>, [">= 0.37"])
    else
      s.add_dependency(%q<couchrest>, [">= 0.37"])
    end
  else
    s.add_dependency(%q<couchrest>, [">= 0.37"])
  end
end

